from typing import Protocol


class TofinoBackend(Protocol):
    def status(self) -> bool: ...
    def read_all(self) -> list[tuple[int, int]]: ...
    def write_entry(self, ingress_dev: int, egress_dev: int) -> None: ...
    def delete_entry(self, ingress_dev: int) -> None: ...
    def clear_all(self) -> None: ...
